// <auto-generated />
namespace AuctionWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Cool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cool));
        
        string IMigrationMetadata.Id
        {
            get { return "201506052201406_Cool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
